# Generated by Django 4.0.5 on 2023-03-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('N', 'not decided')], max_length=11)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('insurance_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
