# Generated by Django 4.0.5 on 2023-03-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('U', 'undecided')], max_length=1),
        ),
        migrations.AddConstraint(
            model_name='clients',
            constraint=models.CheckConstraint(check=models.Q(('gender__in', ['M', 'F', 'U'])), name='tech_task_clients_genders_valid'),
        ),
    ]
