# Generated by Django 4.0.5 on 2023-03-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_task', '0003_client_insurance_delete_clients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='client_id',
            new_name='client',
        ),
    ]
